### ISSUE TITLE
[保留]Start Offset Frame-No を右にドラッグした際に最終フレームでクリップして欲しい

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#11]
Start Offset Frame-No を右にドラッグした際に最終フレームでクリップして欲しいです。

-------------------
Yitsuse san wrote:
あと、ドラッグした際のクリップなのですが……どうも値をクリップしただけではダメみたいです。
一応ソース上にintスライダ（こちらだと最小値と最大値を指定できる）にかえてみた注釈も残してありますが、最大値クリップの場合は、Unity側で0位置に戻されてしまうようです（スライダでも同じ症状が起こりましたのと、スライダの場合最大値になると強制的に0位置に戻る場合があるようなので、逆に混乱を招くと思いましたのでIntの数値入力形式に戻してあります）。
もし、Int設定領域でのドラッグの際のクリップ方法についてご存じであればご教示下さいますと助かります。
-----------------
SS wrote:
そういえば、クリップについては一工夫した記憶があります。

SS4P を見たところ、Editor クラスを継承したSsSpriteEditor クラスを作って、
その中で DrawDefaultInspector() でUnityにデフォルトのインスペクタ項目を表示させた後に、
MonoBehaviour を継承したSsSprite クラスのフレーム値のプロパティをクリップしてますね。

SsSpriteEditor には、フレーム値のプロパティのキャッシュを持っていて、
変更があったときだけSsSpriteの更新処理を呼ぶ、などとしており、
そうしないとUnity側で値をループされてしまうのかもしれません。

なかなか面倒くさそうなのでこれは保留にしましょう。
------------------

**Comment by DKAlpha** [comment]
開発初期の予定なのでクローズします。
