### ISSUE TITLE
インスタンスを配置する際にアクセス違反が発生する

### ISSUE THREAD

**Issue by segsegth** [SpriteStudio/SS5PlayerForUnity#147]
環境はSpriteStudio_ver5.3.6 SSPlayer_1.2.16 Unity_v4.6です。
何度かインスタンスを配置、削除をくりかえしているとアクセス違反が発生するようになり、
SSも落ちてしまうようになりました、
いろいろ試してみたところ、すでに他のアニメに配置済みのインスタンスをコピー、
別のアニメにペーストで配置することで、アクセス違反を回避できるようになりました。
しかし、どこにも配置してないインスタンスをアニメリストから新たに配置することができません。

**Comment by MasamiYitsuse** [comment]
segsegth様

お世話になっております。
1.2.16で、一部状況下におきまして、ドローコールの最適化処理でMeshCombine時に例外が発生する症状が確認されております（Unityのエディタ上のみの症状です）。

現在GitHubのDevelopブランチに公開されている1.2.17ではその症状は解消されております。

もし、当該症状である場合、お手数ですが1.2.17に更新していただけると状況が解消されると思われます。

また、更新ができない状況等である場合、ご一報いただければ、パッチ等の紹介をさせていただきたく思います。

お忙しいなかお手数とは存じますが、何卒ご検討のほどお願い致します。

**Comment by segsegth** [comment]
ご返信ありがとうございます。
SSPlayer側ではなく、SS本体での症状です。
Unityでの再生は問題ありません。

**Comment by DKAlpha** [comment]
申し訳ございませんがこちらにはSS5PlayerForUnityについての投稿をお願いいたします。
本体についての問い合わせは
http://www.webtech.co.jp/help/ja/spritestudio/
こちらのページの問い合わせからからお願いいたします。

こちらの投稿はクローズといたしますので、よろしくお願いいたします。
