### ISSUE TITLE
再生終了のコールバックでnullになる。

### ISSUE THREAD

**Issue by Hayatara** [SpriteStudio/SS5PlayerForUnity#196]
Script_SpriteStudio_Root m_RootScene;
Script_SpriteStudio_ControlPrefab m_SceneController;

bool root = m_RootScene.FunctionPlayEnd (m_RootScene, m_SceneController.gameObject);

上記で再生終了のコールバックを受け取ろうとしたところ、
rootにはfalseが帰ってきて、ログを取っても、参照にnullの思い当たる節がでてきません。

何か設定が必要でしょうか。

**Comment by Hayatara** [comment]
解決しました

**Comment by DKAlpha** [comment]
もしよろしければほかのユーザー様へ原因を共有していただけると幸いです。
難しい場合はクローズしていただいて構いませんのでよろしくお願いいたします。

**Comment by DKAlpha** [comment]
こちらクローズとさせていただきます。
