### ISSUE TITLE
GALAXY NEXUS(SC-04D)にてCPU使用率が高い

### ISSUE THREAD

**Issue by tdsawada** [SpriteStudio/SS5PlayerForUnity#26]
GALAXY NEXUS(SC-04D)にて、SS5を利用した所、非常に高負荷となりました。
Profilerでの確認では、
Script_SpriteStudio_PartsRoot.LateUpdate()→Destroy
について、高いCPU使用率な事を確認しています。
特に画面全体に5レイヤー程で描画をするオブジェクトで、
顕著に問題が発生しています。

**Comment by DKAlpha** [comment]
特定端末についての調査が難しい事と、v1.0から現状のv1.2.16まででかなりの改修を行っておりますので、クローズとさせていただきます。
