### ISSUE TITLE
複数のアニメーションを同時に適用したい

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#3]
メインアニメとしてwait 状態のアニメがあるとします。

ルートパーツに対してXY移動だけ適用した move_anime があるとします。
これをサブアニメとして指定することで移動アニメが追加で適用されるような仕組みです。

同じくカラーブレンドも白くフラッシュ、ダメージ時に赤くフラッシュなどするだけのアニメを作っておき、
メインアニメが持つ全パーツに適用する、またはパーツ名が一致するものだけ適用する、といった事がしたいです。

備忘のため取り急ぎ登録させて頂きました。

**Comment by DKAlpha** [comment]
開発初期の予定なのでクローズいたします。
