### ISSUE TITLE
再インポートを簡単にできるようにして欲しいです

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#34]
## 理由
- ファイル選択ダイアログは .sspj の場所をすぐ忘れる
- メニューからのクリック数が多い…
- Confirm overwrite-prefab のチェックを毎回外すのが面倒

## 希望動作
- 例えば、sspj をインポートしたら インポート元を記憶した、.asset かプレハブがインポート先フォルダのルートに作られ、次回からそれを選択し、再インポートボタンを押すと再インポート、など。
- Cofirm ... チェック状態は記憶して欲しい(Unity起動中の間だけでもOK)
 * 859ebf5 で対応

**Comment by DKAlpha** [comment]
バッチインポート機能が付き自動化されましたのでクローズとします。
