### ISSUE TITLE
データサイズの削減

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#38]
インポート時補間計算方式に変更したため、逆にデータサイズが増える結果になっています。
これはもちろん仕様上そうなるものですが、何らか現状(v1.0) で作られるデータを
小さくする余地はありますでしょうか？

処理が複雑化しますが、例えば、負荷の軽い曲線補間以外の補間方法、
線形、加速、減速はランタイムで処理するなど…

**Comment by DKAlpha** [comment]
v1.2.16にて圧縮機能が付きましたのでクローズとします。
