### ISSUE TITLE
インポート設定のチェック状態が記憶されない？

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#43]
エンバグかな、と思ったのですが、違うみたいでした。
Confirm Import Settings など確か、static にして、起動中だけ記憶するよう
こちらで修正したつもりだったのですが、不完全だったようです。
現状一度ゲーム開始すると、上記設定の変数は初期化されれ true状態に戻っているみたいなのですが、
これを、Unity 起動中だけチェック状態を維持するように対応お願いできますか？

**Comment by DKAlpha** [comment]
対応完了なのでクローズといたします。
