### ISSUE TITLE
インスタンスのアニメーションの終了位置が異なる場合がある。

### ISSUE THREAD

**Issue by MasamiYitsuse** [SpriteStudio/SS5PlayerForUnity#59]
インスタンスを使用したアニメーションの再生が、「時間満了で終了した」場合に、インスタンスで呼び出されているアニメーションの停止フレームが（SS上でのプレビューと比較して）+1ないし-1の状態で停止することがあります。

発生確率:
ジャストで停止する場合と半々位

発生環境:
CPU: Core-i7(3770K) 3.5GHz
Memory: 32GB
GPU: nVIDIA GeForce GTX 770 / VRAM 4GB
OS: Windows7
Unity: ver. 3.57
SS5PU: ver1.1RC1a (2014/10/3 早朝版)

**Comment by DKAlpha** [comment]
情報が古いためクローズとします。
