### ISSUE TITLE
cript_SpriteStudio_PartsRootのFrameNoNowに意図しない大きな値が入る

### ISSUE THREAD

**Issue by Serendy** [SpriteStudio/SS5PlayerForUnity#65]
Debug.Log(cript_SpriteStudio_PartsRoot.FrameNoNow);
これを、Consoleで確認すると、最初のフレームに500くらいの値が入ってしまいます

**Comment by DKAlpha** [comment]
旧バージョンである（バージョン情報が不明）事と現象を確認できませんしたので、クローズといたします。
