### ISSUE TITLE
デシリアライズの挙動を考慮したテーブルに変更する

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#72]
## why
メモリ消費量の節約

## how
アニメーションテーブルの各フレームに格納している「参照（ポインタ）」を「テーブルのインデックス」に変更し、同じオブジェクトへの参照が別のオブジェクトとしてデシリアライズされることを防ぐ。
データサイズもインデックス＜参照となればいくらか縮む可能性はある。

**Comment by DKAlpha** [comment]
対応済なのでクローズにします。
