### ISSUE TITLE
同じssae 内の別のアニメに属するユーザーデータがコールバックされる

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS5PlayerForUnity#76]
```C++
test.ssae
  anime_1   どこかのパーツにユーザーデータのキーあり 整数値：1
  anime_2   どこかのパーツにユーザーデータのキーあり 整数値：2
  anime_3   どこかのパーツにユーザーデータのキーあり 整数値：3

SsRootPart.AnimationStop(); // 停止
SsRootPart.FunctionUserData += OnUserData; // コールバック指定
SsRootPart.AnimationPlay(2,1); // anime_3 のみ再生

void OnUserData(...int AnimationNo...Library_SpriteStudio.KeyFrame.ValueUser.Data Data...)
{
  // 問題
  //３回呼ばれる。
  // Data.NumberInt には 1, 2, 3 が入っているのでanime_1, anime_2 が呼ばれているように見える。
  // なお、AnimationNo には常に2( anime_3 を示す)が入っている
}
```
テストデータあります。

**Comment by MasamiYitsuse** [comment]
コミット: 7d73363cabe4875abbce3b415a8aa70ee5dd32ba [7d73363]
にて、「ピンポン再生＋逆再生＋高速再生」時にフレームスキップ分のコールバックがおかしくなる点についても解消しました。
また、若干「ピンポン再生＋正方向再生」時のフレームスキップ時のコールバックの処理も若干修正しました。

**Comment by DKAlpha** [comment]
SsRootPart.AnimationStop(); // 停止
SsRootPart.FunctionUserData += OnUserData; // コールバック指定
SsRootPart.AnimationPlay(2,1); // anime_3 のみ再生

上のコードを実行すると、日本語コメントの影響でコードが正しく解釈されなくなり、再生していないアニメのユーザーが取得される現象を確認しています。
再生していないアニメのユーザーデータが取得されてしまう場合は、日本語コメントの部分を
・日本語コメントを消す
・最後に半角スペースを付加する
・行間に改行を挿入する
などで意図した動作になる場合がある事を補足します。

**Comment by MasamiYitsuse** [comment]
上記補足です。

「//」で日本語注釈を入れた場合、MonoDevelop+Unityの場合、末尾に「.」（半角ピリオド）を入れると、解消できる場合が少なくないことを付記させて頂きます。
